export const FETCH_RESTRAUNTS 				= 'FETCH_RESTRAUNTS';
export const FETCH_RESTRAUNTS_SUCCESS = 'FETCH_RESTRAUNTS_SUCCESS';
export const FETCH_RESTRAUNTS_FAIL 		= 'FETCH_RESTRAUNTS_FAIL';
export const UPDATE_RESTRAUNTS 				= 'UPDATE_RESTRAUNTS';

export const FETCH_PHOTO 					= 'FETCH_PHOTO';
export const FETCH_PHOTO_SUCCESS 	= 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTO_FAIL 		= 'FETCH_PHOTO_FAIL';

export const ADD_FAVORITE 		= 'ADD_FAVORITE';
export const REMOVE_FAVORITE 	= 'REMOVE_FAVORITE';
