export const FETCH_RESTRAUNTS 				= 'FETCH_RESTRAUNTS';
export const FETCH_RESTRAUNTS_SUCCESS = 'FETCH_RESTRAUNTS_SUCCESS';
export const FETCH_RESTRAUNTS_FAIL 		= 'FETCH_RESTRAUNTS_FAIL';
export const UPDATE_RESTRAUNTS 				= 'UPDATE_RESTRAUNTS';

export const ADD_FAVORITE 		= 'ADD_FAVORITE';
export const REMOVE_FAVORITE 	= 'REMOVE_FAVORITE';
